---
    - name: Enforce Windows user settings
      hosts: windows
      gather_facts: no
      vars:
        state: "0"
      tasks:
        - name: (Re)Create empty file for storage of information
          local_action:
            module: copy
            dest: /tmp/user_settings_enforcement.txt
            content: "\"username\",\"hostname\",\"ip/dns\",\"changed\"\n"
          run_once: True

        - name: Get host's hostname
          raw: "hostname"
          register: hostname

        - name: Create user with provided credentials
          win_user:
            name: "{{ username }}"
            password: "{{ password }}"
            state: present
          when: state=="0"
          notify: Log changed hosts

        - name: Remove user
          win_user:
            name: "{{ username }}"
            state: absent
          when: state=="1"

        - name: Get ansible_host content
          set_fact:
            machine_name: "{{ ansible_host }}"

      handlers:
        - name: Log changed hosts
          local_action:
            module: lineinfile
            line: "{{ '\"' + username + '\",\"' + hostname.stdout | replace('\n','') | regex_replace('\\s*','') | string + '\",\"' + machine_name + '\",\"' + 'true\"' }}"
            dest: /tmp/user_settings_enforcement.txt
            insertafter: EOF
          notify: Send file to final location
            
        - name: Send file to final location
          local_action:
            module: shell
            cmd: "mv -f /tmp/user_settings_enforcement.txt /tmp/playbook_results/user_settings_enforcement.csv"
          become: false
          run_once: True